use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :guiltySpark_web, GuiltySparkWeb.Endpoint,
  http: [:inet6, port: {:system, "PORT"}],
  url: [host: {:system, "NODE_IP"}, port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: "."

config :guiltySpark, GuiltySpark.Repo,
  username: "digital_db",
  password: "Qazwsx123456",
  database: "guiltyspark",
  hostname: "10.0.3.101",
  pool_size: 10



config :logger, level: :info

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
#import_config "prod.secret.exs"
